Ensure secure boot is enabled for Shielded VMs
GoogleCloudPlatform/inspec-gcp-cis-benchmark pull request #83
Opened 2021-03-24 10:20 UTC by szamfirov

A brief summary of the changes:

- Adding one extra check for making sure secure boot is enabled for
Shielded VMs.
- Changing the title of the control (probably bad copy-paste).
- Updating the `inspec-gcp-helpers` dependency to the latest version.

**Note**: The versioning in `inspec-gcp-helpers` is a inconsistent. Some tags are starting with `v1...` others are starting with `1...`.

2021-03-24 10:21 UTC, szamfirov commented
@binamov @KonradSchieban , whenever you have time 👍 Please let me know if I need to address something in the PR.

2021-03-26 01:42 UTC, KonradSchieban commented
/gcbrun

2021-03-26 01:49 UTC, KonradSchieban reviewed
Thanks for the fixes! As always, really appreciate your work!

2021-03-26 01:49 UTC, KonradSchieban commented on controls/4.08-vms.rb
> +        it 'should have secure boot enabled' do
I am not sure about this one. I left it out intentionally because per CIS benchmark it's marked as optional.

2021-03-26 01:50 UTC, KonradSchieban commented
@binamov do we want to validate secure boot if it's marked optional? Maybe we do but with impact 'None'?

2021-03-27 22:24 UTC, aaronlippold commented on controls/4.08-vms.rb
> +        it 'should have secure boot enabled' do
If we can test it - we should test it. We can label it optional in the describe block but even that would be a bit overkill in my opinion

2021-03-27 22:24 UTC, aaronlippold commented on controls/4.08-vms.rb
>            expect(instance_object.shielded_instance_config.enable_integrity_monitoring).to be true
I think the new convention in rspec is `truthy`

2021-03-27 22:26 UTC, aaronlippold commented on inspec.yml
> +version: 1.1.0-27
Any reason we are using `-##` given that the version pattern for CIS is `x.y`

`1.1.27` would keep things in line ... I am not sure `inspec` understands the `x.y.z-##` pattern for the lock and an archive file.

2021-03-27 22:26 UTC, aaronlippold requested changes
small questions

2021-03-28 03:01 UTC, KonradSchieban commented on inspec.yml
> +version: 1.1.0-27
I agree that the -## pattern looks a bit awkward. I believe when we started versioning we took the 1.1.0 release as it shows on the cover of the CIS benchmark guide:

![image](https://user-images.githubusercontent.com/6935519/112741060-27092b00-8f50-11eb-9108-c001af40fe08.png)

2021-03-28 19:44 UTC, KonradSchieban approved these changes

2021-04-01 22:40 UTC, merged