Skip cis-gcp-1.4-iam if zero service account found
GoogleCloudPlatform/inspec-gcp-cis-benchmark pull request #93
Opened 2022-05-20 15:53 UTC by igoratappsatori

Get rid of profile error if there are no profiles found for a project. Just set its impact to none and skip.

2022-05-23 16:36 UTC, KonradSchieban commented
Hi @igoratappsatori , thank you for the PR! Looks good and makes total sense to include that check. Please accept the CLA and we can go forward with merging.

2022-05-23 16:38 UTC, KonradSchieban approved these changes

2022-06-28 19:23 UTC, binamov commented
Hi @igoratappsatori I'd love to merge this change. Any chance you can accept the CLA? https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/pull/93/checks?check_run_id=6527879129

2022-06-28 19:24 UTC, binamov approved these changes
🍔

2022-06-28 19:26 UTC, igoratappsatori commented
Hi @binamov, sure, done ✅ (thank you for your kind reminder)

2022-06-30 21:28 UTC, rbclark requested changes

2022-06-30 21:28 UTC, rbclark commented on controls/1.04-iam.rb
> +        impact 'none'
If the user has multiple service accounts, this will set the impact to 'none' if the last account happens to have a service account. This seems incorrect since it would mean the last users key count would determine the whole control's impact.

<img width="1876" alt="Screen Shot 2022-06-30 at 5 19 50 PM" src="https://user-images.githubusercontent.com/2308869/176780367-f30687db-2606-4757-a71b-5cec6c044938.png">

I would suggest setting the default impact to 'none' and then setting the impact to 'medium' in the one case where this is applicable, similar to how was done in https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/pull/97

2022-08-30 16:51 UTC, closed without merging